services:
  - type: web
    name: todo-backend
    env: node
    buildCommand: npm install
    startCommand: node api/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://todo-frontend.onrender.com

  - type: web
    name: todo-frontend
    env: node
    buildCommand: cd Frontend && npm install && npm run build
    startCommand: cd Frontend && npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://todo-backend.onrender.com
