services:
  - type: web
    name: todo-app
    env: node
    buildCommand: |
      npm install
      cd Frontend
      npm install
      npm run build
    startCommand: node api/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
